# Generated by Django 2.1.4 on 2019-02-06 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(choices=[(0, False), (1, True)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClsCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(choices=[(0, False), (1, True)], default=1)),
                ('cls', models.ForeignKey(limit_choices_to={'enable': 1}, on_delete=django.db.models.deletion.CASCADE, to='teaching.Cls')),
            ],
        ),
        migrations.CreateModel(
            name='ClsStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, '未决定'), (1, '学习中'), (2, '结业'), (3, '肄业')], default=0)),
                ('enable', models.BooleanField(choices=[(0, False), (1, True)], default=1)),
                ('cls', models.ForeignKey(limit_choices_to={'enable': 1}, on_delete=django.db.models.deletion.CASCADE, to='teaching.Cls')),
                ('creator', models.ForeignKey(default=1, limit_choices_to={'enable': 1, 'role__gt': 0}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ClsStudentCreator', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'enable': 1, 'role': 0}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('language', models.IntegerField(choices=[(0, '未定'), (1, '综合'), (2, 'PASCAL'), (3, 'C'), (4, 'C++')], default=0)),
                ('grade', models.IntegerField(choices=[(0, '未定'), (1, '综合'), (2, '小学'), (3, '初中'), (4, '高中')], default=0)),
                ('description', models.TextField(default='')),
                ('create_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(choices=[(0, False), (1, True)], default=1)),
                ('creator', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(default='', max_length=200, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('task', models.BooleanField(choices=[(0, False), (1, True)], default=0)),
                ('create_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(choices=[(0, False), (1, True)], default=1)),
                ('cls', models.ForeignKey(limit_choices_to={'enable': 1}, on_delete=django.db.models.deletion.CASCADE, to='teaching.Cls')),
                ('creator', models.ForeignKey(default=1, limit_choices_to={'enable': 1, 'role__gt': 0}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CurriculumCreator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('description', models.TextField(default='')),
                ('create_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(choices=[(0, False), (1, True)], default=1)),
                ('creator', models.ForeignKey(default=1, limit_choices_to={'enable': 1, 'role__gt': 0}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(limit_choices_to={'enable': 1}, on_delete=django.db.models.deletion.CASCADE, to='teaching.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametype', models.IntegerField(choices=[(0, '酷町猫'), (1, '酷町打字')], default=0)),
                ('gsid', models.IntegerField(default=0)),
                ('gcid', models.IntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(choices=[(0, False), (1, True)], default=1)),
                ('creator', models.ForeignKey(default=1, limit_choices_to={'enable': 1, 'role': 0}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(limit_choices_to={'enable': 1}, on_delete=django.db.models.deletion.DO_NOTHING, to='teaching.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('create_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(choices=[(0, False), (1, True)], default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teaching.Course')),
                ('creator', models.ForeignKey(default=1, limit_choices_to={'enable': 1, 'role__gt': 0}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametype', models.IntegerField(choices=[(0, '酷町猫'), (1, '酷町打字')], default=0)),
                ('gcid', models.IntegerField(default=0)),
                ('gsid', models.IntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(choices=[(0, False), (1, True)], default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(limit_choices_to={'enable': 1}, on_delete=django.db.models.deletion.DO_NOTHING, to='teaching.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('send_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('scene', models.IntegerField(choices=[(0, '登陆'), (1, '注册'), (2, '忘记密码')], null=True)),
                ('used', models.IntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=20)),
                ('cp_name', models.CharField(default=None, max_length=20)),
                ('smsid', models.CharField(default=None, max_length=64)),
                ('secret_sign', models.CharField(default=None, max_length=64)),
                ('compute_sign', models.CharField(default=None, max_length=64)),
                ('send_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('scene', models.IntegerField(choices=[(0, '登陆'), (1, '注册'), (2, '忘记密码')])),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teaching.SMS')),
            ],
        ),
        migrations.CreateModel(
            name='UserTeachingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('name', models.CharField(default='', max_length=50)),
                ('sex', models.IntegerField(choices=[(0, '女'), (1, '男')], default=0)),
                ('role', models.IntegerField(choices=[(0, '学生'), (1, '教学老师'), (2, '教务老师'), (3, '教务主任'), (4, '教学主任'), (99, '管理员'), (100, 'root')], default=0)),
                ('age', models.IntegerField(default=None, null=True)),
                ('grade', models.IntegerField(choices=[(0, '未知'), (1, '小一'), (2, '小二'), (3, '小三'), (4, '小四'), (5, '小五'), (6, '小六'), (7, '初一'), (8, '初二'), (9, '初三'), (10, '高一'), (11, '高二'), (12, '高三')], default=0)),
                ('creator', models.IntegerField(default=-1)),
                ('description', models.TextField(default='', null=True)),
                ('login_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(choices=[(0, False), (1, True)], default=1)),
                ('ip', models.CharField(default=None, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='lesson',
            field=models.ForeignKey(limit_choices_to={'enable': 1}, on_delete=django.db.models.deletion.CASCADE, to='teaching.Lesson'),
        ),
        migrations.AddField(
            model_name='comment',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.Homework'),
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'enable': 1, 'role': 0}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CommentStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clscourse',
            name='course',
            field=models.ForeignKey(limit_choices_to={'enable': 1}, on_delete=django.db.models.deletion.CASCADE, to='teaching.Course'),
        ),
        migrations.AddField(
            model_name='clscourse',
            name='creator',
            field=models.ForeignKey(default=1, limit_choices_to={'enable': 1, 'role__gt': 0}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ClsCourseCreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clscourse',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'enable': 1, 'role__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cls',
            name='courses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'enable': 1}, through='teaching.ClsCourse', to='teaching.Course'),
        ),
        migrations.AddField(
            model_name='cls',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ClsCreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cls',
            name='students',
            field=models.ManyToManyField(blank=True, through='teaching.ClsStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cls',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ClsTeacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
