# Generated by Django 2.1.4 on 2019-02-06 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kudingmao.models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('enable', models.BooleanField(default=False)),
                ('btn_enable', models.CharField(default='', max_length=500)),
                ('type', models.IntegerField(choices=[(0, '普通'), (1, '考试')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('map', models.FileField(blank=True, null=True, upload_to=kudingmao.models.map_directory_path)),
                ('hint', markdownx.models.MarkdownxField(default='')),
                ('idx', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JudgeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='')),
                ('origin_code', models.TextField(default='')),
                ('result', models.CharField(max_length=1000)),
                ('result_code', models.IntegerField(default=0)),
                ('output', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('judge_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('submit_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('fish_count', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('verbose_name', models.CharField(max_length=100)),
                ('time_limit', models.IntegerField(choices=[(100, '100ms'), (1000, '1s'), (2000, '2s'), (3000, '3s'), (4000, '4s'), (5000, '5s'), (6000, '6s'), (7000, '7s'), (8000, '8s'), (9000, '9s'), (10000, '10s')], default=100)),
                ('memory_limit', models.IntegerField(choices=[(131072, '128MB'), (65536, '64MB')], default=131072)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.IntegerField(choices=[(1, '主角'), (2, '敌人'), (3, '友军'), (4, '道具')], default=1)),
                ('range', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StageLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_lines', models.IntegerField(default=0)),
                ('fish_count', models.IntegerField(default=0)),
                ('hint', markdownx.models.MarkdownxField(default='')),
                ('default_code', models.TextField(blank=True, default='')),
                ('type', models.IntegerField(choices=[(0, '普通'), (1, '补全')], default=0)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudingmao.Lang')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudingmao.GameStage')),
            ],
        ),
        migrations.CreateModel(
            name='StageRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_x', models.IntegerField(default=0)),
                ('ord_y', models.IntegerField(default=0)),
                ('dir', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudingmao.Role')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudingmao.GameStage')),
            ],
        ),
        migrations.CreateModel(
            name='StageRoleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
                ('stagerole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudingmao.StageRole')),
            ],
        ),
        migrations.CreateModel(
            name='UserLangChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudingmao.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='UserLangStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters', models.ManyToManyField(related_name='userlang_chapters', through='kudingmao.UserLangChapter', to='kudingmao.Chapter')),
                ('lang', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kudingmao.Lang')),
                ('last_stage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kudingmao.GameStage')),
                ('new_chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kudingmao.Chapter')),
                ('new_stage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userlangstage_new_stage', to='kudingmao.GameStage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudingmao.Lang')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStagesStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_score', models.IntegerField(default=0)),
                ('lang', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kudingmao.Lang')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudingmao.GameStage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kudingmao.GameStage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userlangchapter',
            name='userlangstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudingmao.UserLangStage'),
        ),
        migrations.AddField(
            model_name='judgerecord',
            name='code_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudingmao.Lang'),
        ),
        migrations.AddField(
            model_name='judgerecord',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kudingmao.GameStage'),
        ),
        migrations.AddField(
            model_name='judgerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='stages',
            field=models.ManyToManyField(to='kudingmao.GameStage'),
        ),
        migrations.AlterUniqueTogether(
            name='userstagestatus',
            unique_together={('user', 'stage')},
        ),
        migrations.AlterUniqueTogether(
            name='userstagesstatistic',
            unique_together={('user', 'stage', 'lang')},
        ),
        migrations.AlterUniqueTogether(
            name='userlangstage',
            unique_together={('user', 'lang')},
        ),
        migrations.AlterUniqueTogether(
            name='userlangchapter',
            unique_together={('userlangstage', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='stagerolestatus',
            unique_together={('stagerole', 'key')},
        ),
        migrations.AlterIndexTogether(
            name='stagerole',
            index_together={('stage', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='stagelang',
            unique_together={('stage', 'lang')},
        ),
        migrations.AlterIndexTogether(
            name='judgerecord',
            index_together={('user', 'stage')},
        ),
    ]
